version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    container_name: postgres  
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - 3000:3000
    depends_on:
      - db
  
  locust:
    image: locustio/locust:latest
    command: -f /mnt/locustfile.py --host http://app:3000 --headless -u 10 -r 2 -t 30s --html=/mnt/locust_reports/locust_report.html
    profiles:
      - load-testing
    volumes:
      - ./locust/performance-test.py:/mnt/locustfile.py
      - ./locust_reports:/mnt/locust_reports
    ports:
      - 8089:8089